/*
 * PrettyPrintEnum_WIN.h
 *
 *  Created on: 01/05/2012
 *      Author: Johannes
 */

#pragma once

#include <iostream>
#include <Windows.h>

#define FG_BOLD FOREGROUND_INTENSITY
#define BG_BOLD BACKGROUND_INTENSITY

namespace frontend
{

enum BG_COLOR {
	BG_BLACK = 0,
	BG_RED = BACKGROUND_RED,
	BG_GREEN = BACKGROUND_GREEN,
	BG_YELLOW = BACKGROUND_GREEN | BACKGROUND_BLUE,
	BG_BLUE = BACKGROUND_BLUE,
	BG_MAGENTA = BACKGROUND_RED | BACKGROUND_BLUE,
	BG_WHITE = BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_GREEN
};

enum FG_COLOR {
	FG_BLACK = 0,
	FG_RED = FOREGROUND_RED,
	FG_GREEN = FOREGROUND_GREEN,
	FG_YELLOW = FOREGROUND_GREEN | FOREGROUND_BLUE,
	FG_BLUE = FOREGROUND_BLUE,
	FG_MAGENTA = FOREGROUND_RED | FOREGROUND_BLUE,
	FG_WHITE = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_GREEN
};



}